name: Release

on:
  push:
    branches:
      - main

jobs:
  versions:
    name: Versioning
    runs-on: ubuntu-latest
    steps:
      - name: Download source code
        uses: actions/checkout@v2
      - name: Configure git
        runs: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Bump version
        uses: qzb/standard-version@v1
