name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy.yml
      - localization/**/*
      - common/**/*

jobs:
  versions:
    name: Versioning
    runs-on: ubuntu-latest
    steps:
      - name: Download source code
        uses: actions/checkout@v2
      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Bump version
        uses: qzb/standard-version-action@v1.0.1
      - name: Push
        run: git push --follow-tags origin main
